### ISSUE TITLE
[Issue]: Duplicate entries in ES-DE when saving multiple times, with disabled "delete existing files"

### ISSUE THREAD

**Issue by donsdgr81** [BinaryQuantumSoul/esde_android_apps#1]
When I try to save my apps and android games that I chose, after reloading ES-DE, I get multiple entries of each app.

**Comment by BinaryQuantumSoul** [comment]
I need more details ?
Settings? screenshots?

It might be due to not having "delete existing files" checked combined with the system to prevent apps overwriting each other when sharing same name

**Comment by donsdgr81** [comment]
@BinaryQuantumSoul - you are coorect. The "delete existing files" was not enabled in my settings. Apologies.

**Comment by BinaryQuantumSoul** [comment]
No worries, you found an interesting bug as "delete existing files" cannot be enabled with disabled "check path names"
