### ISSUE TITLE
Why does the app insist on the ROM folder named "ROMs" (with capitalization as shown)?

### ISSUE THREAD

**Issue by dburr** [BinaryQuantumSoul/esde_android_apps#2]
On my RP4Pro's SD card, my ROMs directory is named "roms" (all lowercase) but I am unable to select it because the app complains "the selected directory is not named ROMs." Capitalization shouldn't matter on a FAT32 or exFAT formatted SD card. I went in and renamed it, so everything works now, but this seems like an odd thing to enforce.

**Comment by BinaryQuantumSoul** [comment]
> On my RP4Pro's SD card, my ROMs directory is named "roms" (all lowercase) but I am unable to select it because the app complains "the selected directory is not named ROMs." Capitalization shouldn't matter on a FAT32 or exFAT formatted SD card. I went in and renamed it, so everything works now, but this seems like an odd thing to enforce.
> 

You can disable it in settings. But it was because by default it deletes the whole androidapps directory when you save to take into account when some apps are uninstalled. Obviously if someone selects the wrong folder I don't want them to lose all their data
